apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: soumyadipr/authentication-service:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9010
      serviceAccount: spring-cloud-microservice    
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  selector:
    app: authentication-service
  type: ClusterIP  
  ports:
  - port: 9010
    targetPort: 9010
    protocol: TCP