apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: soumyadipr/inventory-service:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9040
      serviceAccount: spring-cloud-microservice    
      restartPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  type: ClusterIP  
  ports:
  - port: 9040
    targetPort: 9040
    protocol: TCP