apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: soumyadipr/order-service:0.0.6.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9030
      serviceAccount: spring-cloud-microservice      
      restartPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  type: ClusterIP  
  ports:
  - port: 9030
    targetPort: 9030
    protocol: TCP
