apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: soumyadipr/product-service:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9020
      serviceAccount: spring-cloud-microservice        
      restartPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  type: ClusterIP  
  ports:
  - port: 9020
    targetPort: 9020
    protocol: TCP