server:
  port: 9040

spring:  application:    name: inventory-service  
  zipkin:
    base-url: http://35.184.144.97:9411  
  cloud:    
    kubernetes:
      enabled: true
      discovery:
        enabled: true     h2:    console:      enabled: true  datasource:    url: jdbc:h2:mem:inventory_db
      
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultzone: http://localhost:8761/eureka 
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}    