INSERT INTO INVENTORY VALUES(1, 'I_PHONE_12_RED', 50);
INSERT INTO INVENTORY VALUES(2, 'I_PHONE_12_GOLD', 5);
INSERT INTO INVENTORY VALUES(3, 'I_PHONE_12_GREY', 80);
INSERT INTO INVENTORY VALUES(4, 'I_PHONE_11_RED', 80);
INSERT INTO INVENTORY VALUES(5, 'I_PHONE_11_GREY', 10);
